server:
  port: 8000
#  port: ${random.int(10000,51000)}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: first-service22
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

